# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import inference_pb2 as inference__pb2


class DetectObjectStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.DetectObject = channel.unary_unary(
        '/DetectObject/DetectObject',
        request_serializer=inference__pb2.ImageFile.SerializeToString,
        response_deserializer=inference__pb2.ImageFile.FromString,
        )


class DetectObjectServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def DetectObject(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DetectObjectServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'DetectObject': grpc.unary_unary_rpc_method_handler(
          servicer.DetectObject,
          request_deserializer=inference__pb2.ImageFile.FromString,
          response_serializer=inference__pb2.ImageFile.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'DetectObject', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
