# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='inference.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0finference.proto\"\x1a\n\tImageFile\x12\r\n\x05image\x18\x01 \x01(\x0c\x32\x38\n\x0c\x44\x65tectObject\x12(\n\x0c\x44\x65tectObject\x12\n.ImageFile\x1a\n.ImageFile\"\x00\x62\x06proto3')
)




_IMAGEFILE = _descriptor.Descriptor(
  name='ImageFile',
  full_name='ImageFile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='ImageFile.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=45,
)

DESCRIPTOR.message_types_by_name['ImageFile'] = _IMAGEFILE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageFile = _reflection.GeneratedProtocolMessageType('ImageFile', (_message.Message,), dict(
  DESCRIPTOR = _IMAGEFILE,
  __module__ = 'inference_pb2'
  # @@protoc_insertion_point(class_scope:ImageFile)
  ))
_sym_db.RegisterMessage(ImageFile)



_DETECTOBJECT = _descriptor.ServiceDescriptor(
  name='DetectObject',
  full_name='DetectObject',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=47,
  serialized_end=103,
  methods=[
  _descriptor.MethodDescriptor(
    name='DetectObject',
    full_name='DetectObject.DetectObject',
    index=0,
    containing_service=None,
    input_type=_IMAGEFILE,
    output_type=_IMAGEFILE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DETECTOBJECT)

DESCRIPTOR.services_by_name['DetectObject'] = _DETECTOBJECT

# @@protoc_insertion_point(module_scope)
